### ISSUE TITLE
Error 3501 (Bad Request)

### ISSUE THREAD

**Issue by link1107** [centrifugal/centrifuge-java#38] opened 2022-07-26 21:40 UTC
Hello!
I am trying to connect to Centrifugo-server to receive messages with donation-events.
The server owners provide a script for JS, which perectly works for JS:

```
 <script src="https://cdn.jsdelivr.net/gh/centrifugal/centrifuge-js@2.X.X/dist/centrifuge.min.js"></script>
    <script>
        async function start() {
            // Creating Centrifuge object
            window.centrifuge = new Centrifuge('wss://centrifugo.donatepay.ru:43002/connection/websocket', {
                subscribeEndpoint: 'https://donatepay.ru/api/v2/socket/token',
                subscribeParams:   {
                    access_token: 'od13l807htY4zXSDlWsV8n3BvpOExBIGoLTs9JXqWKzxf0ZrxVTZpcL87vL6'
                },
                disableWithCredentials: true
            });

            // Providing Centrifuge token
            centrifuge.setToken(await getToken())

            // Subscribing to user $public:USER_ID
            centrifuge.subscribe("$public:162386", function (message) {
                // Printing all new messages to console
                console.log('message', message);
            });

            centrifuge.on('error', (e) => {
                console.log('error', e)
            })

            centrifuge.on('subscribe', (e) => {
                console.log('subscribe', e)
            })

            centrifuge.on('connect', (e) => {
                console.log(e)
            })

            // Connecting to Centrifugo
            centrifuge.connect();
        }
```

So i tired to replicate it on Java. Here is my code:

```
        EventListener listener = new EventListener() {
            @Override
            public void onConnected(Client client,  ConnectedEvent event) {
                if (isItFirstSuccessfulConnection) {
                    logToConsole("Произведено успешное подключение к §b" + donationServiceToken.getDonationServiceType() + "§f!");
                    isItFirstSuccessfulConnection = false;
                } else {
                    logToConsole("Восстановлено соединение с §b" + donationServiceToken.getDonationServiceType() + "§f!");
                }
            }

            @Override
            public void onDisconnected(Client client, DisconnectedEvent event) {
                if (isActive) {
                    logToConsole("Потеряно соединение с §b" + donationServiceToken.getDonationServiceType() + "§f!");
                }
            }
        };

        Options options = new Options();
        options.setToken(centrifugeToken);
        
        centrifugoClient = new Client(SOCKET_SERVER, options, listener);
        
        centrifugoClient.connect();

        SubscriptionEventListener subListener = new SubscriptionEventListener() {
            @Override
            public void onJoin(Subscription sub, JoinEvent event) {
                logToConsole("Успешная подписка на канал " + sub.getChannel());
            }
            @Override
            public void onError(Subscription sub, SubscriptionErrorEvent event) {
                logToConsole("Ошибка подписки на канал " + sub.getChannel() + "! Причина: " + event.getError().getMessage());
            }
            @Override
            public void onPublication(Subscription sub, PublicationEvent event) {
                String data = new String(event.getData(), UTF_8);
                logToConsole("Получено сообщение: " + data);
            }
        };

        Subscription sub;
        try {
            sub = centrifugoClient.newSubscription("$public:"+userId, subListener);
        } catch (DuplicateSubscriptionException e) {
            e.printStackTrace();
            return;
        }
        sub.subscribe();
```

So when i try to launch the plugin (this code is a part of Minecraft plugin), i gets an error (3501, Bad Request) right after the "centrifugoClient.connect();" (it goes to DisconnectedListener and gives the error message i've mentioned above).

Server version is 3.2.0, my client version is 0.2.2

Could you give me any advice please? Thank you in advance.

**Comment by link1107** [comment] 2022-07-26 23:33
Also tried to do the same with 0.1.0 and older versions, and i have noticed, that `client.setToken()` method is not working. I've checked in a debug mode, and found, that however a token's String object is correct, after applying `client.setToken(token);` the "token" field of client remains empty (just like "").

Token String value:
![2022-07-27_01-31-34](https://user-images.githubusercontent.com/66795347/181129668-5f12637f-13a8-497e-9a9f-7d8ea59c76ef.png)

Client "token" field value after applying setToken() method:
![2022-07-27_01-31-54](https://user-images.githubusercontent.com/66795347/181129684-03c5c299-46ee-43c4-81fb-38f12ff9c740.png)
.

**Comment by link1107** [comment] 2022-07-26 23:39
If i got it right, while executing setToken(), some NullPointerException is thrown.

![2022-07-27_01-36-28](https://user-images.githubusercontent.com/66795347/181130081-e214e828-891a-4fa0-b7ab-86e06db3acfb.png)

**Comment by FZambia** [comment] 2022-07-27 04:34
Hello!

We released Centrifugo v4. Which uses new client protocol version by default.

In your case `centrifuge-js@2.X.X` uses client protocol v1, Java client >= 0.2.0 uses client protocol v2.

All information can be found in links:

1. [Release post](https://centrifugal.dev/blog/2022/07/19/centrifugo-v4-released)
2. [Migration guide](https://centrifugal.dev/docs/getting-started/migration_v4)
3. [Centrifugo v4 release notes](https://github.com/centrifugal/centrifugo/releases/tag/v4.0.0)
4. [centrifuge-java v0.2.2 release notes](https://github.com/centrifugal/centrifuge-java/releases/tag/0.2.2)

If you want to work in a way similar to JS client you need to use centrifuge-java v0.1.0 (which has different API compared to v0.2.2). v0.1.0 does not support all Centrifugo features, only those mentioned in [feature matrix](https://github.com/centrifugal/centrifuge-java/tree/0.1.0#feature-matrix).

**Comment by link1107** [comment] 2022-07-27 06:08
Hello!
Thank you for your reply.
I also trief 0.1.0 and got the same 3501 error "Bad Request". I can't figure out why.

**Comment by FZambia** [comment] 2022-07-27 08:15
Server logs should contain the reason. Do you have access to them?

**Comment by link1107** [comment] 2022-07-27 14:16
No, i dont have. Server owners dont want to share. So i have no idea, what is the reason. They just said thait server version is v3, thats all.

**Comment by FZambia** [comment] 2022-07-27 14:22
Could you post the minimal code with 0.1.0 that reproduces the problem for you? Maybe I'll be able to find the reason just looking at it, at least I can try :)

**Comment by FZambia** [comment] 2022-07-27 15:51
Well, no quick ideas. One thing I see that you are using private channel but not defining onPrivateSub callback https://github.com/centrifugal/centrifuge-java/blob/2b3c332c864deff3dcc54e676ef819bdd585c948/centrifuge/src/main/java/io/github/centrifugal/centrifuge/EventListener.java#L45

But it should not result into Bad Request error - it should result into `private subscribe error` disconnect reason in 0.1.0.

**Comment by FZambia** [comment] 2022-07-27 15:57
Could you write to me in Telegram? My nickname there is FZambia – will be more simple to debug

**Comment by link1107** [comment] 2022-07-27 16:09
Yep, just have sent a message

**Comment by FZambia** [comment] 2022-07-31 09:54
We found that the reason was missing onPrivateSub callback definition. Also, we found that Javascript example of donatepay does not properly work (returns `unknown channel` error - i.e. `public` namespace not defined there).

Closing, since nothing to do here.

**Closed by FZambia** 2022-07-31 09:54 UTC
