### ISSUE TITLE
How to make Centrifugo disconnect after 30 seconds of no Internet connection?

### ISSUE THREAD

**Issue by UrielFrankel** [centrifugal/centrifuge-java#65] opened 2023-09-04 08:46 UTC
What I need is an onError callback after 30 seconds.
I see all these methods:

```
    /**
     * Set custom timeout for requests in milliseconds. By default, 5000 is used.
     */
    public void setTimeout(int timeout) {
        this.timeout = timeout;
    }


    /**
     * Set minimal time before reconnect attempt in milliseconds. By default, 500 is used.
     */
    public void setMinReconnectDelay(int minReconnectDelay) {
        this.minReconnectDelay = minReconnectDelay;
    }

    
    /**
     * Set max time between reconnect attempts in milliseconds. By default, 20000 is used.
     */
    public void setMaxReconnectDelay(int maxReconnectDelay) {
        this.maxReconnectDelay = maxReconnectDelay;
    }

   
    /**
     * Set max time of ping delay from server in milliseconds. By default, 10000 is used.
     */
    public void setMaxServerPingDelay(int maxServerPingDelay) {
        this.maxServerPingDelay = maxServerPingDelay;
    }

```
But I still don't understand which should I use for this requirement?
Thanks.

**Comment by FZambia** [comment] 2023-09-06 05:09
Seems like a duplicate of https://github.com/centrifugal/centrifuge-js/issues/248

**Comment by UrielFrankel** [comment] 2023-09-06 06:46
@FZambia My Problem is that I get immediately `Client.EventListener.onError`. How can I tell in that moment that I am in the reconnecting stage?

**Comment by FZambia** [comment] 2023-09-06 18:13
You can listen `disconnected` event (EventListener.onDisconnected) and react on it I suppose.  `onError` is mostly for logging purposes.

**Comment by UrielFrankel** [comment] 2023-09-06 19:43
@FZambia  Can I be sure that I will be in the 3 states: Connected, Connecting, Disconnected? 
I am afraid that my app will hang since I will be in onError state and won't continue to onDisconnected()

**Comment by FZambia** [comment] 2023-09-07 05:13
All possible client state listed here: https://github.com/centrifugal/centrifuge-java/blob/f11c20c54e9a0a91af44c4597a005ce2a2cd40c7/centrifuge/src/main/java/io/github/centrifugal/centrifuge/ClientState.java#L4

See also https://centrifugal.dev/docs/transports/client_api#client-connection-states which describes possible state transitions.

There is no `error` state, `onError` does not signal about state transition - it's just a callback that signals about various async errors while client works. If client was connected and then connection is lost client goes to connecting state if connection loss is temporary and to disconnected state if connection loss is permanent.

My advice about using `disconnected` event is misleading actually - in your case you most probably want to put logic on `connecting` state event.

**Comment by UrielFrankel** [comment] 2023-09-07 11:00
So, I will put a timer in onConnecting for 30 seconds, and disable it at onConnected.

**Comment by FZambia** [comment] 2023-09-07 17:47
Yes, I think it will work.

**Comment by FZambia** [comment] 2023-09-19 04:22
Did this work @UrielFrankel ?

**Comment by UrielFrankel** [comment] 2023-09-19 04:52
No.

**Comment by FZambia** [comment] 2023-09-19 04:53
Can you provide details why?

**Comment by UrielFrankel** [comment] 2023-09-19 09:23
I used all of them on my android app and then turned off the wifi and the timeout was not calling disconnect after 30 seconds. I even put a breakpoints in the right places and it wasn't called. btw, unrelated issue: SubscriptionTokenGetter calling super causes error... It took me time to figure it out.

**Comment by FZambia** [comment] 2023-09-19 10:12
> I used all of them on my android app and then turned off the wifi and the timeout was not calling disconnect after 30 seconds.

Did you receive `connecting` event after turning off wi-fi?

**Comment by UrielFrankel** [comment] 2023-09-19 13:19
I need to get disconnect after 30 seconds. I need a way to timeout the reconnecting and tell the user his connection dropped.

**Comment by FZambia** [comment] 2023-10-10 04:27
Closing since no response from op for a long time

**Closed by FZambia** 2023-10-10 04:27 UTC
